import{a as v,S,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const q="11450328-c2e7c4daa2322168e3859ef5d",E="https://pixabay.com/api/";async function u(o,t){try{return(await v.get(E,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch(r){throw console.error("Sorry, there are no images matching your search query. Please try again!",r),r}}let P=new S(".gallery a",{captionsData:"alt",captionDelay:250});const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".btn-load-more");function p(o){const t=o.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img class="img" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r.likes}</p>
          <p><b>Views:</b> ${r.views}</p>
          <p><b>Comments:</b> ${r.comments}</p>
          <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),P.refresh()}function R(){f.innerHTML=""}function y(){m.classList.remove("is-hidden")}function g(){m.classList.add("is-hidden")}function b(){h.classList.remove("is-hidden-btn")}function L(){h.classList.add("is-hidden-btn")}const w=document.querySelector(".js-form"),B=w.elements["search-text"],M=document.querySelector(".btn-load-more");let n=1,i="",l=0;w.addEventListener("submit",async o=>{if(o.preventDefault(),i=B.value.trim(),n=1,!!i){y(),R(),L();try{const t=await u(i,n);if(l=t.totalHits,t.hits.length===0){a.warning({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(t.hits),n*15<l&&b()}catch{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}}});M.addEventListener("click",async()=>{n++,y(),L();try{const o=await u(i,n);p(o.hits),n*15>=l?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):b(),O()}catch{a.error({title:"Error",message:"Could not fetch more images.",position:"topRight"})}finally{g()}});function O(){const o=document.querySelector(".gallery-item");if(!o)return;const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
